# Generated by Django 4.1.2 on 2023-03-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('ville', models.CharField(max_length=50)),
                ('quartier', models.CharField(max_length=200)),
                ('Nom_propio', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='meubles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('ville', models.CharField(max_length=50)),
                ('quartier', models.CharField(max_length=200)),
                ('Nom_entreprise', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
