# Generated by Django 4.1.2 on 2023-04-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meubles',
            options={'ordering': ['-date_added']},
        ),
    ]
