# Generated by Django 4.1.2 on 2023-04-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0002_alter_meubles_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='Nom_propio',
            new_name='Nom_proprio',
        ),
    ]
