# Generated by Django 4.1.2 on 2023-04-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0003_rename_nom_propio_house_nom_proprio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='meubles',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
