# Generated by Django 4.1.2 on 2023-04-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0004_alter_house_image_alter_meubles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.CharField(choices=[('M', 'Maison'), ('A', 'Studio'), ('S', 'Studio'), ('C', 'Chambre')], default='categorie', max_length=30),
        ),
    ]
