# Generated by Django 4.1.2 on 2023-04-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0005_house_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={},
        ),
    ]
