# Generated by Django 4.1.2 on 2023-04-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0006_alter_house_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-h_date_added']},
        ),
        migrations.AlterModelOptions(
            name='meubles',
            options={'ordering': ['-m_date_added']},
        ),
        migrations.RenameField(
            model_name='house',
            old_name='Nom_proprio',
            new_name='h_Nom_proprio',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='category',
            new_name='h_category',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='date_added',
            new_name='h_date_added',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='description',
            new_name='h_description',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='image',
            new_name='h_image',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='price',
            new_name='h_price',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='quartier',
            new_name='h_quartier',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='ville',
            new_name='h_ville',
        ),
        migrations.RenameField(
            model_name='meubles',
            old_name='Nom_entreprise',
            new_name='m_Nom_entreprise',
        ),
        migrations.RenameField(
            model_name='meubles',
            old_name='date_added',
            new_name='m_date_added',
        ),
        migrations.RenameField(
            model_name='meubles',
            old_name='description',
            new_name='m_description',
        ),
        migrations.RenameField(
            model_name='meubles',
            old_name='image',
            new_name='m_image',
        ),
        migrations.RenameField(
            model_name='meubles',
            old_name='price',
            new_name='m_price',
        ),
        migrations.RenameField(
            model_name='meubles',
            old_name='quartier',
            new_name='m_quartier',
        ),
        migrations.RenameField(
            model_name='meubles',
            old_name='ville',
            new_name='m_ville',
        ),
    ]
